version: "3.8"

volumes:
  postgres-data:

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: window-fns
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
